/*
 * My first Calculator in Java
 */
package myfirstcalculator;

/**
 * @author Adrian Manole
 */
public class MyFirstCalculator extends javax.swing.JFrame {
    
    double number;
    double answer;
    int calculation;
    

    /**
     * Creates new form MyFirstCalculator
     */
    
    public MyFirstCalculator() {
        initComponents();
        buttonOn.setEnabled(false); //Application starts with ON button disabled
    }
    
    /**
     * Arithmetic operations which will be performed by the application
     * case 1 - addition (+), case 2 - subtraction (-), case 3 - mutiplication (*)
     * case 4 - division (/)
     */
    
    
    public void arithmeticOperations (){
        
        switch(calculation){
            
            case 1: // Addition
                answer = number + Double.parseDouble(calculatorScreen.getText());
                calculatorScreen.setText(Double.toString(answer));
                break;
                
            case 2: // Subtraction
                answer = number - Double.parseDouble(calculatorScreen.getText());
                calculatorScreen.setText(Double.toString(answer));
                break;
                
            case 3: // Multiplication
                answer = number * Double.parseDouble(calculatorScreen.getText());
                calculatorScreen.setText(Double.toString(answer));
                break;
                
            case 4: // Division
                answer = number / Double.parseDouble(calculatorScreen.getText());
                calculatorScreen.setText(Double.toString(answer));
                break;
                
        }
    }
    
  /**
   * When the Off radio button is selected all buttons and calculator screen
   * are disabled, only the On button is enabled.
   */
    
    public void turnCalculatorOff () {
        
        calculatorScreen.setEnabled(false);
        buttonZero.setEnabled(false);
        buttonOne.setEnabled(false);
        buttonTwo.setEnabled(false);
        buttonThree.setEnabled(false);
        buttonFour.setEnabled(false);
        buttonFive.setEnabled(false);
        buttonSix.setEnabled(false);
        buttonSeven.setEnabled(false);
        buttonEight.setEnabled(false);
        buttonNine.setEnabled(false);
        buttonClear.setEnabled(false);
        buttonBack.setEnabled(false);
        buttonMinus.setEnabled(false);
        buttonPlus.setEnabled(false);
        buttonMultiply.setEnabled(false);
        buttonDivide.setEnabled(false);
        buttonEquals.setEnabled(false);
        buttonPoint.setEnabled(false);
        buttonOff.setEnabled(false);
        buttonOn.setEnabled(true); //On button enabled
        
    }
    
    /**
     * When ON radio button is selected all buttons and calculator screen
     * are enabled, and the On button becomes disabled.
     */
    
    public void turnCalculatorOn (){
        
        buttonOn.setEnabled(false); //On button disabled
        calculatorScreen.setEnabled(true);
        buttonZero.setEnabled(true);
        buttonOne.setEnabled(true);
        buttonTwo.setEnabled(true);
        buttonThree.setEnabled(true);
        buttonFour.setEnabled(true);
        buttonFive.setEnabled(true);
        buttonSix.setEnabled(true);
        buttonSeven.setEnabled(true);
        buttonEight.setEnabled(true);
        buttonNine.setEnabled(true);
        buttonClear.setEnabled(true);
        buttonBack.setEnabled(true);
        buttonMinus.setEnabled(true);
        buttonPlus.setEnabled(true);;
        buttonMultiply.setEnabled(true);
        buttonDivide.setEnabled(true);
        buttonEquals.setEnabled(true);
        buttonPoint.setEnabled(true);
        buttonOff.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        calculatorScreen = new javax.swing.JTextField();
        buttonOn = new javax.swing.JRadioButton();
        buttonOff = new javax.swing.JRadioButton();
        buttonBack = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonSeven = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();
        buttonEight = new javax.swing.JButton();
        buttonNine = new javax.swing.JButton();
        buttonFour = new javax.swing.JButton();
        buttonFive = new javax.swing.JButton();
        buttonSix = new javax.swing.JButton();
        buttonOne = new javax.swing.JButton();
        buttonTwo = new javax.swing.JButton();
        buttonThree = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        buttonMultiply = new javax.swing.JButton();
        buttonDivide = new javax.swing.JButton();
        buttonZero = new javax.swing.JButton();
        buttonPoint = new javax.swing.JButton();
        buttonEquals = new javax.swing.JButton();
        arithmeticOperatorLabel = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setForeground(new java.awt.Color(102, 102, 102));
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        calculatorScreen.setEditable(false);
        calculatorScreen.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        calculatorScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        calculatorScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorScreenActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonOn);
        buttonOn.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        buttonOn.setText("ON");
        buttonOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOnActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonOff);
        buttonOff.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        buttonOff.setText("OFF");
        buttonOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOffActionPerformed(evt);
            }
        });

        buttonBack.setFont(new java.awt.Font("Courier New", 1, 28)); // NOI18N
        buttonBack.setText("←");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        buttonClear.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonClear.setText("C");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        buttonSeven.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonSeven.setText("7");
        buttonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSevenActionPerformed(evt);
            }
        });

        buttonPlus.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonPlus.setText("+");
        buttonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlusActionPerformed(evt);
            }
        });

        buttonEight.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonEight.setText("8");
        buttonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEightActionPerformed(evt);
            }
        });

        buttonNine.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonNine.setText("9");
        buttonNine.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNineActionPerformed(evt);
            }
        });

        buttonFour.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonFour.setText("4");
        buttonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFourActionPerformed(evt);
            }
        });

        buttonFive.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonFive.setText("5");
        buttonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiveActionPerformed(evt);
            }
        });

        buttonSix.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonSix.setText("6");
        buttonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSixActionPerformed(evt);
            }
        });

        buttonOne.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonOne.setText("1");
        buttonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOneActionPerformed(evt);
            }
        });

        buttonTwo.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonTwo.setText("2");
        buttonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwoActionPerformed(evt);
            }
        });

        buttonThree.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonThree.setText("3");
        buttonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThreeActionPerformed(evt);
            }
        });

        buttonMinus.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonMinus.setText("-");
        buttonMinus.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinusActionPerformed(evt);
            }
        });

        buttonMultiply.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonMultiply.setText("*");
        buttonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplyActionPerformed(evt);
            }
        });

        buttonDivide.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonDivide.setText("/");
        buttonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivideActionPerformed(evt);
            }
        });

        buttonZero.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonZero.setText("0");
        buttonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZeroActionPerformed(evt);
            }
        });

        buttonPoint.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonPoint.setText(".");
        buttonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPointActionPerformed(evt);
            }
        });

        buttonEquals.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        buttonEquals.setText("=");
        buttonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqualsActionPerformed(evt);
            }
        });

        arithmeticOperatorLabel.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        arithmeticOperatorLabel.setForeground(new java.awt.Color(255, 51, 102));
        arithmeticOperatorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculatorScreen)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(buttonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(buttonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(buttonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(buttonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(buttonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(buttonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(buttonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(buttonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(buttonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(buttonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonOn)
                                        .addComponent(buttonOff))
                                    .addGap(18, 18, 18)
                                    .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(arithmeticOperatorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(arithmeticOperatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculatorScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonOn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonOff)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculatorScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorScreenActionPerformed

    }//GEN-LAST:event_calculatorScreenActionPerformed

    /**
     * When the "7" button is clicked number 7 is displayed on the calculator 
     * screen
     */
    
    private void buttonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSevenActionPerformed
        calculatorScreen.setText(calculatorScreen.getText() + "7");
    }//GEN-LAST:event_buttonSevenActionPerformed
    
    /**
     * When the On button is selected the application is turned On.
     */
    
    private void buttonOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOnActionPerformed
        turnCalculatorOn();
    }//GEN-LAST:event_buttonOnActionPerformed

    /**
     * When the Off button is selected the application is turned OFF.
     */
    
    private void buttonOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOffActionPerformed
        turnCalculatorOff();
    }//GEN-LAST:event_buttonOffActionPerformed

    /**
     * When the ← (back button) is clicked it erases one character at a time
     * from the calculator screen.
     */
    
    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        int length = calculatorScreen.getText().length();
        int number = calculatorScreen.getText().length() - 1;
        String store;
        
        if (length > 0){
            StringBuilder back = new StringBuilder (calculatorScreen.getText());
            back.deleteCharAt(number);
            store = back.toString();
            calculatorScreen.setText(store);
        }
    }//GEN-LAST:event_buttonBackActionPerformed

    /**
     * When the "2" button is clicked number 2 is displayed on the calculator 
     * screen.
     */
    
    private void buttonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwoActionPerformed
        calculatorScreen.setText(calculatorScreen.getText() + "2");
    }//GEN-LAST:event_buttonTwoActionPerformed

    /**
     * When the "0" button is clicked number 0 is displayed on the calculator 
     * screen.
     */
    
    private void buttonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZeroActionPerformed
        calculatorScreen.setText(calculatorScreen.getText() + "0");
    }//GEN-LAST:event_buttonZeroActionPerformed

    /**
     * When the "1" button is clicked number 1 is displayed on the calculator 
     * screen.
     */
    
    private void buttonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOneActionPerformed
        calculatorScreen.setText(calculatorScreen.getText() + "1");
    }//GEN-LAST:event_buttonOneActionPerformed

    /**
     * When the "3" button is clicked number 3 is displayed on the calculator 
     * screen.
     */
    
    private void buttonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThreeActionPerformed
        calculatorScreen.setText(calculatorScreen.getText() + "3");
    }//GEN-LAST:event_buttonThreeActionPerformed

    /**
     * When the "4" button is clicked number 4 is displayed on the calculator 
     * screen.
     */
    
    private void buttonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFourActionPerformed
        calculatorScreen.setText(calculatorScreen.getText() + "4");
    }//GEN-LAST:event_buttonFourActionPerformed

    /**
     * When the "5" button is clicked number 5 is displayed on the calculator 
     * screen.
     */
    
    private void buttonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiveActionPerformed
        calculatorScreen.setText(calculatorScreen.getText() + "5");
    }//GEN-LAST:event_buttonFiveActionPerformed

    /**
     * When the "6" button is clicked number 6 is displayed on the calculator 
     * screen.
     */
    
    private void buttonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSixActionPerformed
        calculatorScreen.setText(calculatorScreen.getText() + "6");
    }//GEN-LAST:event_buttonSixActionPerformed

    /**
     * When the "8" button is clicked number 8 is displayed on the calculator 
     * screen.
     */
    
    private void buttonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEightActionPerformed
        calculatorScreen.setText(calculatorScreen.getText() + "8");
    }//GEN-LAST:event_buttonEightActionPerformed

    /**
     * When the "9" button is clicked number 9 is displayed on the calculator 
     * screen.
     */
    
    private void buttonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNineActionPerformed
        calculatorScreen.setText(calculatorScreen.getText() + "9");
    }//GEN-LAST:event_buttonNineActionPerformed

    /**
     * When the "+" button is clicked the characters which are displayed at that 
     * given moment on the calculator screen and the arithmetic operator "+" will be
     * displayed on the arithmetic operator label, above the calculator screen.
     */
    
    private void buttonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlusActionPerformed
        number = Double.parseDouble(calculatorScreen.getText());
        calculation = 1; // case 1 from arithmeticOperations method
        calculatorScreen.setText("");
        arithmeticOperatorLabel.setText(number + " +");
    }//GEN-LAST:event_buttonPlusActionPerformed

    /**
     * When the "-" button is clicked the characters which are displayed at 
     * that given moment on the calculator screen and the arithmetic operator "-"
     * will be displayed on the arithmetic operator label, above the calculator screen.
     */
    
    private void buttonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinusActionPerformed
        number = Double.parseDouble(calculatorScreen.getText());
        calculation = 2; // case 1 from arithmeticOperations method
        calculatorScreen.setText("");
        arithmeticOperatorLabel.setText(number + " -");
    }//GEN-LAST:event_buttonMinusActionPerformed

    /**
     * When the "*" button is clicked the characters which are displayed at that given 
     * moment on the calculator screen and the arithmetic operator "*" will be
     * displayed on the arithmetic operator label, above the calculator screen.
     */
    
    private void buttonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplyActionPerformed
        number = Double.parseDouble(calculatorScreen.getText());
        calculation = 3; // case 3 from arithmeticOperations method
        calculatorScreen.setText("");
        arithmeticOperatorLabel.setText(number + " *");
    }//GEN-LAST:event_buttonMultiplyActionPerformed

    /**
     * When the "/" button is clicked the characters which are displayed at that given 
     * moment on the calculator screen and the arithmetic operator "/" will be
     * displayed on the arithmetic operator label, above the calculator screen.
     */
    
    private void buttonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivideActionPerformed
        number = Double.parseDouble(calculatorScreen.getText());
        calculation = 4; // case 4 from arithmeticOperations method
        calculatorScreen.setText("");
        arithmeticOperatorLabel.setText(number + " /");
    }//GEN-LAST:event_buttonDivideActionPerformed

    /**
     * When the "." button is clicked one dot will be displayed on the calculator 
     * screen.
     */
    
    private void buttonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPointActionPerformed
        calculatorScreen.setText(calculatorScreen.getText() + ".");
    }//GEN-LAST:event_buttonPointActionPerformed

    /**
     * When the "C" button is clicked it erases everything displayed on the 
     * calculator screen and on the arithmetic operator label.
     */
    
    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        calculatorScreen.setText("");
        arithmeticOperatorLabel.setText("");  
    }//GEN-LAST:event_buttonClearActionPerformed

    /**
     * When the "=" button is clicked the result of the arithmetic operation
     * performed prior is displayed on the calculator screen, at the same time it 
     * erases the characters displayed on the arithmetic operation label 
     * (situated above the calculator screen).
     */
    
    private void buttonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEqualsActionPerformed
        arithmeticOperations ();
        arithmeticOperatorLabel.setText("");
    }//GEN-LAST:event_buttonEqualsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFirstCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFirstCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFirstCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFirstCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyFirstCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arithmeticOperatorLabel;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDivide;
    private javax.swing.JButton buttonEight;
    private javax.swing.JButton buttonEquals;
    private javax.swing.JButton buttonFive;
    private javax.swing.JButton buttonFour;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonMultiply;
    private javax.swing.JButton buttonNine;
    private javax.swing.JRadioButton buttonOff;
    private javax.swing.JRadioButton buttonOn;
    private javax.swing.JButton buttonOne;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JButton buttonPoint;
    private javax.swing.JButton buttonSeven;
    private javax.swing.JButton buttonSix;
    private javax.swing.JButton buttonThree;
    private javax.swing.JButton buttonTwo;
    private javax.swing.JButton buttonZero;
    private javax.swing.JTextField calculatorScreen;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
